### PR TITLE
Refactoring the solution.

### PR DESCRIPTION
**Pull request by fiseni**
I think you got here a lot of changes.
I didn't finish refactoring the QuestionsController intentionally. I prepared the methods in the service. Try to refactor the last two methods in the controller.
After you finish everything, and you can compile the whole solution, you have to create migrations for App and AppIdentity contexts.

### CODE REVIEW

**Comment by fiseni** [comment]
No, I deleted the existing migrations. Should be created from scratch.
I split the contexts, one only for identity, and one for the application. In appsettings.json you have the connection strings for both of them. Finish the app so you can compile it, and then you will create the migrations.

**Comment by Youssef1313** [comment]
@fiseni, Great. I'll read through the changes done here and continue on that. This was really really helpful to me.

Thanks very much :heart:

**Comment by fiseni** [comment]
No problem.
Just so u know, i have used one of my nuget packages for validations. Its based on GuardClauses package, but i have extensions for various types, thats why I use this one for my projects.

Im on twitter as FatiIseni, u can catch up with me there.
Good luck with programming :)

**Comment by Youssef1313** [comment]
Thanks very much for the help. I've completed some refactoring on top of what you've done, and will review what I've done again to check if any other refactoring is needed before adding more features. Your help here is really much appreciated :heart:

**Comment by fiseni** [comment]
Enjoy!
Star and follow, and pass along, so I can help other people too! :)

**Pull request merged**
